#version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  springboot_app:
    build: ./backend
    container_name: event_scheduler
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/event_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - backend

  frontend:
    build: ./frontend  # Ensure frontend directory exists
    container_name: event_frontend
    restart: always
    depends_on:
       - springboot_app
    environment:
      BACKEND_URL: http://springboot_app:8080
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
